logLevel: info

rtsp: true
rtspAddress: :8554
rtspTransports: [tcp]

hls: true
hlsAddress: :8888
hlsEncryption: false
hlsAllowOrigin: "*"

webrtc: true
webrtcAddress: :8889
webrtcEncryption: false
webrtcAllowOrigin: "*"
