const fs = require('fs');
const http = require('http');
const https = require('https');
const path = require('path');
const User = require('../models/User');
const Visitor = require('../models/Visitor');
const EntryLog = require('../models/EntryLog');
const Billing = require('../models/Billing');
const Complaint = require('../models/Complaint');
const FacilityReservation = require('../models/FacilityReservation');
const Admin = require('../models/Admin');
const MasterAdmin = require('../models/MasterAdmin');
const ReportArchive = require('../models/ReportArchive');
const { parsePagination, sendPaginatedResponse } = require('../utils/pagination');
const { storeUploadedFile } = require('../utils/fileStorage');

const isAdminRole = (role) => ['ADMIN', 'MASTER_ADMIN'].includes(role);

const PAGE_WIDTH = 612;
const PAGE_HEIGHT = 792;
const LEFT_MARGIN = 40;
const TOP_START = 750;
const LINE_HEIGHT = 14;
const BOTTOM_MARGIN = 44;
const MAX_LINE_LENGTH = 92;

const normalizeAscii = (value) =>
  String(value ?? '')
    .normalize('NFKD')
    .replace(/[^\x20-\x7E]/g, '');

const escapePdfText = (value) =>
  normalizeAscii(value)
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)');

const wrapLine = (text, maxLength = MAX_LINE_LENGTH) => {
  const source = normalizeAscii(text).trim();
  if (!source) return [''];

  const words = source.split(/\s+/);
  const lines = [];
  let current = '';

  words.forEach((word) => {
    const candidate = current ? `${current} ${word}` : word;
    if (candidate.length <= maxLength) {
      current = candidate;
      return;
    }

    if (current) lines.push(current);
    current = word;
  });

  if (current) lines.push(current);
  return lines;
};

const buildPdfFromLines = (pages) => {
  const fontObjectNumber = 3 + pages.length;
  const objects = [
    '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n',
    `2 0 obj\n<< /Type /Pages /Count ${pages.length} /Kids [${pages.map((_, index) => `${3 + index} 0 R`).join(' ')}] >>\nendobj\n`
  ];

  const contentObjects = [];

  pages.forEach((pageLines, index) => {
    const contentObjectNumber = fontObjectNumber + 1 + index;
    const commands = ['BT', '/F1 11 Tf', `${LINE_HEIGHT} TL`, `${LEFT_MARGIN} ${TOP_START} Td`];

    pageLines.forEach((line, lineIndex) => {
      if (lineIndex > 0) commands.push('T*');
      commands.push(`(${escapePdfText(line)}) Tj`);
    });

    commands.push('ET');
    const contentStream = `${commands.join('\n')}\n`;

    objects.push(
      `${3 + index} 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Resources << /Font << /F1 ${fontObjectNumber} 0 R >> >> /Contents ${contentObjectNumber} 0 R >>\nendobj\n`
    );

    contentObjects.push(
      `${contentObjectNumber} 0 obj\n<< /Length ${contentStream.length} >>\nstream\n${contentStream}endstream\nendobj\n`
    );
  });

  objects.push(`${fontObjectNumber} 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n`);
  objects.push(...contentObjects);

  let pdf = '%PDF-1.4\n';
  const offsets = [0];

  objects.forEach((object) => {
    offsets.push(pdf.length);
    pdf += object;
  });

  const xrefStart = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += '0000000000 65535 f \n';
  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, '0')} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;

  return pdf;
};

const paginateLines = (lines) => {
  const maxLinesPerPage = Math.floor((TOP_START - BOTTOM_MARGIN) / LINE_HEIGHT);
  const pages = [];

  for (let index = 0; index < lines.length; index += maxLinesPerPage) {
    pages.push(lines.slice(index, index + maxLinesPerPage));
  }

  return pages.length ? pages : [['No data available']];
};

const buildReportPdf = (reportData, generatedByName) => {
  const lines = [
    'ECOTREND HOA',
    'Administrative System Report',
    '',
    `Report Title: ${reportData.title}`,
    `Generated On: ${formatDateTime(new Date())}`,
    `Generated By: ${generatedByName || 'ADMIN'}`,
    `Total Records: ${reportData.rows.length}`,
    ''
  ];

  reportData.rows.forEach((row, rowIndex) => {
    lines.push(`Record ${rowIndex + 1}`);
    reportData.headers.forEach((header) => {
      const label = header
        .replace(/([A-Z])/g, ' $1')
        .replace(/_/g, ' ')
        .replace(/^./, (letter) => letter.toUpperCase())
        .trim();

      wrapLine(`${label}: ${row[header] ?? ''}`).forEach((line) => lines.push(line));
    });
    lines.push('');
  });

  const pages = paginateLines(lines);
  return buildPdfFromLines(pages);
};

const formatDateTime = (value) => {
  if (!value) return '';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return '';
  return date.toLocaleString('en-PH', {
    year: 'numeric',
    month: 'short',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit'
  });
};

const formatDateForName = (value = new Date()) => {
  const date = new Date(value);
  const pad = (part) => String(part).padStart(2, '0');
  return [
    date.getFullYear(),
    pad(date.getMonth() + 1),
    pad(date.getDate()),
    pad(date.getHours()),
    pad(date.getMinutes()),
    pad(date.getSeconds())
  ].join('');
};

const buildStoredReportFile = async (filename, fileBase, pdfContent) => {
  const pdfBuffer = Buffer.from(pdfContent, 'binary');

  return storeUploadedFile(
    {
      originalname: filename,
      mimetype: 'application/pdf',
      size: pdfBuffer.length,
      buffer: pdfBuffer
    },
    {
      folder: 'ecotrend-hoa/report-archives',
      localDir: 'uploads/report-archives',
      prefix: fileBase,
      resourceType: 'raw'
    }
  );
};

const getLocalArchivePath = (archive) => {
  if (archive?.file?.storage === 'local' && archive.file.path?.startsWith('/uploads/')) {
    return path.join(__dirname, '..', archive.file.path.replace(/^\//, ''));
  }

  if (archive?.filePath) {
    return archive.filePath;
  }

  return '';
};

const downloadRemoteFile = (url, redirectCount = 0) =>
  new Promise((resolve, reject) => {
    if (redirectCount > 5) {
      reject(new Error('Too many redirects while downloading archived report'));
      return;
    }

    const client = String(url).startsWith('https:') ? https : http;

    const request = client.get(url, (response) => {
      const statusCode = response.statusCode || 0;

      if ([301, 302, 303, 307, 308].includes(statusCode) && response.headers.location) {
        response.resume();
        const nextUrl = new URL(response.headers.location, url).toString();
        resolve(downloadRemoteFile(nextUrl, redirectCount + 1));
        return;
      }

      if (statusCode < 200 || statusCode >= 300) {
        response.resume();
        reject(new Error(`Remote archive download failed with status ${statusCode}`));
        return;
      }

      const chunks = [];
      response.on('data', (chunk) => chunks.push(chunk));
      response.on('end', () => {
        resolve({
          buffer: Buffer.concat(chunks),
          contentType: response.headers['content-type'] || 'application/octet-stream'
        });
      });
    });

    request.on('error', reject);
  });

const resolveAdminName = async (userId, role) => {
  if (!userId) return role || 'ADMIN';

  if (role === 'MASTER_ADMIN') {
    const masterAdmin = await MasterAdmin.findById(userId).select('username').lean();
    return masterAdmin?.username || 'MASTER_ADMIN';
  }

  const admin = await Admin.findById(userId).select('username').lean();
  return admin?.username || role || 'ADMIN';
};

const buildResidentsReport = async () => {
  const residents = await User.find({ isApproved: true }).lean();
  const headers = [
    'residentName',
    'username',
    'email',
    'address',
    'street',
    'phoneNumber',
    'familyMembersCount',
    'vehiclesCount',
    'joinedAt'
  ];

  const rows = residents.map((resident) => ({
    residentName: resident.familyName || '',
    username: resident.username || '',
    email: resident.email || '',
    address: resident.houseAddress || '',
    street: resident.street || '',
    phoneNumber: resident.phoneNumber || '',
    familyMembersCount: resident.familyMembers?.length || 0,
    vehiclesCount: resident.vehicles?.filter((vehicle) => !vehicle.deletedAt).length || 0,
    joinedAt: formatDateTime(resident.createdAt)
  }));

  return {
    title: 'Residents Report',
    headers,
    rows
  };
};

const buildVisitorsReport = async () => {
  const visitors = await Visitor.find({}).sort({ createdAt: -1 }).lean();
  const headers = [
    'visitorName',
    'purpose',
    'hostResident',
    'hostAddress',
    'contactNumber',
    'vehiclePlateNumber',
    'vehicleType',
    'status',
    'expectedDate',
    'entryTime',
    'exitTime',
    'createdAt'
  ];

  const rows = visitors.map((visitor) => ({
    visitorName: visitor.name || '',
    purpose: visitor.purpose || '',
    hostResident: visitor.hostResidentName || '',
    hostAddress: visitor.hostResidentAddress || '',
    contactNumber: visitor.contactNumber || '',
    vehiclePlateNumber: visitor.vehiclePlateNumber || '',
    vehicleType: visitor.vehicleType || '',
    status: visitor.status || '',
    expectedDate: formatDateTime(visitor.expectedDate),
    entryTime: formatDateTime(visitor.entryTime),
    exitTime: formatDateTime(visitor.exitTime),
    createdAt: formatDateTime(visitor.createdAt)
  }));

  return {
    title: 'Visitors Report',
    headers,
    rows
  };
};

const buildBillingReport = async () => {
  const billings = await Billing.find({})
    .populate('residentId', 'familyName username houseAddress street phoneNumber')
    .lean();

  const headers = [
    'residentName',
    'username',
    'address',
    'year',
    'month',
    'monthlyDue',
    'paid',
    'paymentStatus',
    'paymentMethod',
    'orNumber',
    'datePaid',
    'remarks'
  ];

  const rows = [];

  billings.forEach((billing) => {
    const resident = billing.residentId || {};
    Object.entries(billing.months || {}).forEach(([month, monthRecord]) => {
      rows.push({
        residentName: resident.familyName || '',
        username: resident.username || '',
        address: [resident.houseAddress, resident.street].filter(Boolean).join(', '),
        year: billing.year,
        month,
        monthlyDue: billing.monthlyDue ?? '',
        paid: monthRecord?.paid ? 'Yes' : 'No',
        paymentStatus: monthRecord?.paymentStatus || 'none',
        paymentMethod: monthRecord?.paymentMethod || '',
        orNumber: monthRecord?.orNumber || '',
        datePaid: monthRecord?.datePaid || '',
        remarks: monthRecord?.remarks || ''
      });
    });
  });

  return {
    title: 'Billing Report',
    headers,
    rows
  };
};

const buildEntryLogsReport = async () => {
  const entryLogs = await EntryLog.find({})
    .populate('guardOnDuty', 'username fullName')
    .populate('residentId', 'familyName houseAddress street phoneNumber')
    .sort({ timestamp: -1 })
    .lean();

  const headers = [
    'timestamp',
    'logType',
    'plateNumber',
    'vehicleOwnerType',
    'ownerName',
    'residentName',
    'residentAddress',
    'vehicleType',
    'vehicleColor',
    'guardOnDuty',
    'notes'
  ];

  const rows = entryLogs.map((log) => ({
    timestamp: formatDateTime(log.timestamp),
    logType: log.logType || '',
    plateNumber: log.plateNumber || '',
    vehicleOwnerType: log.vehicleOwnerType || '',
    ownerName: log.ownerName || '',
    residentName: log.residentName || log.residentId?.familyName || '',
    residentAddress:
      log.residentAddress ||
      [log.residentId?.houseAddress, log.residentId?.street].filter(Boolean).join(', '),
    vehicleType: log.vehicleType || '',
    vehicleColor: log.vehicleColor || '',
    guardOnDuty: log.guardOnDuty?.fullName || log.guardOnDuty?.username || '',
    notes: log.notes || ''
  }));

  return {
    title: 'Entry and Exit Logs Report',
    headers,
    rows
  };
};

const buildComplaintsReport = async () => {
  const complaints = await Complaint.find({}).sort({ createdAt: -1 }).lean();
  const headers = [
    'complaintType',
    'complainantName',
    'complainantAddress',
    'againstPersonName',
    'subject',
    'location',
    'message',
    'status',
    'adminResponse',
    'internalRemarks',
    'hasPhoto',
    'isArchived',
    'submittedAt'
  ];

  const rows = complaints.map((complaint) => ({
    complaintType: complaint.complaintType || '',
    complainantName: complaint.complainantName || '',
    complainantAddress: complaint.complainantAddress || '',
    againstPersonName: complaint.againstPersonName || '',
    subject: complaint.subject || '',
    location: complaint.location || '',
    message: complaint.message || '',
    status: complaint.status || '',
    adminResponse: complaint.adminResponse || '',
    internalRemarks: complaint.internalRemarks || '',
    hasPhoto: complaint.photo?.path ? 'Yes' : 'No',
    isArchived: complaint.isArchived ? 'Yes' : 'No',
    submittedAt: formatDateTime(complaint.createdAt)
  }));

  return {
    title: 'Complaints Report',
    headers,
    rows
  };
};

const buildFacilitiesReport = async () => {
  const reservations = await FacilityReservation.find({})
    .sort({ createdAt: -1 })
    .lean();

  const headers = [
    'facilityName',
    'eventType',
    'residentName',
    'residentAddress',
    'dateReserved',
    'endDateTime',
    'durationHours',
    'numberOfGuests',
    'purpose',
    'hourlyRate',
    'totalAmount',
    'paymentRequired',
    'paymentMethod',
    'paymentStatus',
    'status',
    'isPaid',
    'approvedBy',
    'approvedAt',
    'rejectionReason',
    'createdAt'
  ];

  const rows = reservations.map((reservation) => ({
    facilityName: reservation.facilityName || '',
    eventType: reservation.eventType || '',
    residentName: reservation.residentName || '',
    residentAddress: reservation.residentAddress || '',
    dateReserved: formatDateTime(reservation.dateReserved),
    endDateTime: formatDateTime(reservation.endDateTime),
    durationHours: reservation.durationHours ?? '',
    numberOfGuests: reservation.numberOfGuests ?? '',
    purpose: reservation.purpose || '',
    hourlyRate: reservation.hourlyRate ?? '',
    totalAmount: reservation.totalAmount ?? '',
    paymentRequired: reservation.paymentRequired ? 'Yes' : 'No',
    paymentMethod: reservation.paymentMethod || '',
    paymentStatus: reservation.paymentStatus || '',
    status: reservation.status || '',
    isPaid: reservation.isPaid ? 'Yes' : 'No',
    approvedBy: reservation.approvedBy || '',
    approvedAt: formatDateTime(reservation.approvedAt),
    rejectionReason: reservation.rejectionReason || '',
    createdAt: formatDateTime(reservation.createdAt)
  }));

  return {
    title: 'Facility Reservations Report',
    headers,
    rows
  };
};

const reportBuilders = {
  residents: buildResidentsReport,
  visitors: buildVisitorsReport,
  entry_logs: buildEntryLogsReport,
  billing: buildBillingReport,
  complaints: buildComplaintsReport,
  facilities: buildFacilitiesReport
};

exports.getArchivedReports = async (req, res) => {
  try {
    if (!isAdminRole(req.user?.role)) {
      return res.status(403).json({ message: 'Only admins can access archived reports' });
    }

    const reportType = req.query.type;
    const filter = reportType && reportBuilders[reportType] ? { reportType } : {};
    const pagination = parsePagination(req.query);
    const query = ReportArchive.find(filter).sort({ createdAt: -1 }).lean();

    if (pagination.enabled) {
      const [items, total] = await Promise.all([
        query.clone().skip(pagination.skip).limit(pagination.limit),
        ReportArchive.countDocuments(filter)
      ]);
      return sendPaginatedResponse(res, pagination, items, total);
    }

    const archives = await query;
    res.json(archives);
  } catch (error) {
    console.error('Error fetching archived reports:', error);
    res.status(500).json({ message: 'Failed to fetch archived reports' });
  }
};

exports.generateReport = async (req, res) => {
  try {
    if (!isAdminRole(req.user?.role)) {
      return res.status(403).json({ message: 'Only admins can generate reports' });
    }

    const reportType = req.body?.reportType;
    const buildReport = reportBuilders[reportType];

    if (!buildReport) {
      return res.status(400).json({ message: 'Invalid report type' });
    }

    const reportData = await buildReport();
    const timestamp = formatDateForName();
    const fileBase = `${reportType}-report-${timestamp}`;
    const filename = `${fileBase}.pdf`;

    const generatedByName = await resolveAdminName(req.user?.userId, req.user?.role);
    const pdfContent = buildReportPdf(reportData, generatedByName);
    const storedReportFile = await buildStoredReportFile(filename, fileBase, pdfContent);

    const archive = await ReportArchive.create({
      reportType,
      format: 'pdf',
      title: reportData.title,
      filename,
      file: storedReportFile,
      recordCount: reportData.rows.length,
      generatedByRole: req.user?.role || 'ADMIN',
      generatedByName
    });

    res.status(201).json({
      message: 'Report generated successfully',
      archive
    });
  } catch (error) {
    console.error('Error generating report:', error);
    res.status(500).json({ message: 'Failed to generate report' });
  }
};

exports.downloadReport = async (req, res) => {
  try {
    if (!isAdminRole(req.user?.role)) {
      return res.status(403).json({ message: 'Only admins can download archived reports' });
    }

    const archive = await ReportArchive.findById(req.params.id).lean();
    if (!archive) {
      return res.status(404).json({ message: 'Report archive not found' });
    }

    const remoteArchiveUrl = archive.file?.storage === 'cloudinary' ? archive.file.path : '';
    if (remoteArchiveUrl) {
      const remoteFile = await downloadRemoteFile(remoteArchiveUrl);
      res.setHeader('Content-Type', archive.file?.mimetype || remoteFile.contentType || 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename="${archive.filename}"`);
      return res.send(remoteFile.buffer);
    }

    const localArchivePath = getLocalArchivePath(archive);
    if (!localArchivePath || !fs.existsSync(localArchivePath)) {
      return res.status(404).json({ message: 'Archived report file no longer exists' });
    }

    return res.download(localArchivePath, archive.filename);
  } catch (error) {
    console.error('Error downloading report:', error);
    res.status(500).json({ message: 'Failed to download report' });
  }
};
